language: node_js
node_js:
  - '6.3.0'
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
    fi
script:
  - npm run release
  - npm run disttree
  - npm run cucumber
  - npm test
deploy:
  provider: releases
  api_key:
    secure: k5FwHlnzg3lvPogaReW3FpEhsFfpknpKUY0PZlCmwHoYBGNAY+asxSWQ1Aj05Tdi2CPVeP2VgkN1qHtOdkjoo0y/C3YWZOSfjVxnPnKdjI6SGkHn1jfyMcjOuZMErgBCOOfgbNQ5p4C3P5iWLIdnO1hD+zARshp/esJcEHapxvj+DlXGUvq43B2g+PhJb6jKtuybAL46uvqhiI+sdGjrpe/Yc0F/qFi0XU5NUgsTf6DjuERxvw3CDk7ri++ibtCMZIfNnosFCt/+MNVwFavNLl5jrSPKhzIwNUEHdVPIvNV7wiTr+2VWD8XqRllmktawyeGdvmdNRevFgJLMvEXpdIpyvatd/Xl19qrJcNe5ZCYVjRQumylUqvPdZjIkCYsvYI3UCns6Yh9Myefr74A0RbOtCaS7/eblqHgDWKPnwoeEkImohQdHpiS0zN8tVIpjpoCNdaBhugw5bQu6eDEtid3DHV0krbsYfqp4WADboFuyAYJ5lMCAp98FIzWRxXdiA2xOTLmDSwAvmHhjlNIY8zythylUK3xgmo+IIO0t0/ploupFeU9Mw1VfEMlVi5e+5mYfuKCjySg+Xpi+D42zYHZ0vmqOGW1pZ5FKyOqJrzEKlhBTA5vdAmxH4JLdSeqU0wmJhnQrmdugOZ5s4k01N7uDg23YPh1Gq9A6bwprpBA=
  file: "dist/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: tinytacoteam/zazu
